### ISSUE TITLE
Extra search info

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#68] opened 2023-02-03 14:42 UTC
When searching for substr, dropdown shows:
``
routine abs in file Class Cool
``

the "in file" doesn't help the users, and the spacing and font rendering seems weird.

I recommend something like

```
routine abs in class Cool
```

with `abs` highlighted and `class Cool` highlighted, and no extra space before "in", lowercase class (to make it look more like the actual class declaration)

**Comment by coke** [comment] 2023-02-03 14:58
Not sure if this is on master, or only part of the pull request under consideration; not clear which version is running on raku-new

**Comment by coke** [comment] 2023-02-03 17:24
the "in file" may have made sense for the language pages, but even then, say "in <title of page>" is sufficient.

**Comment by finanalyst** [comment] 2023-02-03 17:36
- new-raku is built from another repo: https://github.com/finanalyst/raku-documentation-site-dev
This was where I built the website when I was developing it, and it also contains the older site code.
  - `doc-website` and  `raku-documentation-site-dev` should be exactly the same except that the `more` dropdown contains a link to Collection-examples.
- I agree 'title of page' is a far better idea

**Comment by finanalyst** [comment] 2023-02-03 18:46
About the spacing: this is to differentiate between the 'value' found when filtering using the chars in the search bar, and the extra information available about that particular element.

While what @coke says in first comment is reasonable for a simple method, try `say` in the bar. Now you will get a category 'Heading' and a title about the difference between 'say,put, print', which I think is useful. But the info section is less interesting, other than it tells you which source file it is in.

The different information can be found in `Website/plugins/ogdenwebb/add-search.raku`. It is obviously possible to have different `info` strings for different categories.

Suggestion?

**Comment by coke** [comment] 2023-02-03 19:00
The search shouldn't be returning a heading of "method say in file x" and also a method of "method say in file x" (they differ right now only in how the file name is formatted).

Most of the headings are duplicative here. I'd also move the headings section to the end, as in my experience, I'm more likely to be looking up something by name (so I want 'methods' ahead of headings in that case, e.g.)

For the ones that remain after that cleanup, I'd wrap the heading in quotes, so something like:

```
section "Atomic operations on Scalar" on type Scalar
```

**Comment by finanalyst** [comment] 2023-02-03 19:19
About the highlighting after a cursor down. Plain autocomplete does the highlighting of the menu. Our version is souped up, so the menu-item has been lost.

About putting the extra item info into the search bar: I cannot see how to do that.

Removal of duplicates. This is doable. It may take some time.

Moving Header / Glossary to the end. Will do.

**Comment by finanalyst** [comment] 2023-02-03 23:06
Started working on this.

**Comment by finanalyst** [comment] 2023-02-03 23:42
More consistent with suggestions of @coke
Use of ':' char to differentiate between an entry and information about entry

Looking to see if the auto-focus with cursor motion can be fixed.

**Comment by 2colours** [comment] 2023-02-04 01:43
Added my comments to https://github.com/Raku/doc-website/pull/66, I think they are highly related to this issue.

**Comment by coke** [comment] 2023-02-06 13:53
If there's work to be done on Extended Search, let's open a separate ticket for that (For initial release, we can consider hiding the extended search)

**Comment by finanalyst** [comment] 2023-02-06 14:07
+1 hiding extended search to begin with

**Comment by finanalyst** [comment] 2023-02-10 10:20
The search bar now highlights the drop-down menu, but 
a) hovering over a menu item, and moving a cursor over the menu item interact poorly
b) moving down the menu causing the highlight is not the best styling
c) when the cursor moves to the bottom of a large menu, and the menu is not visible in the window, the menu does not scroll up.

These are all soluble with CSS. The relevant files are in `Website/plugins/search-bar`.

It would be good if someone could have a look and fix these as I am not so good at styling.

**Comment by finanalyst** [comment] 2023-02-10 10:22
@2colours Marton could you look at new-raku.finanalyst.org to see whether there are more issues than the three just mentioned above?

**Comment by finanalyst** [comment] 2023-02-12 23:25
added #96 to improve search bar a bit

**Comment by 2colours** [comment] 2023-02-13 10:38
@finanalyst sorry - yes, I can still produce inconsistencies just by moving the mouse up and down, sometimes hovering the categories. Also, the selected entry still isn't scrolled into view.

**Comment by finanalyst** [comment] 2023-02-14 10:12
@2colours a) not sure quite what you mean by 'inconsistencies'. 
b) moving the cursor with the up/down keys will move the selected element off the bottom of the menu. I have tried very hard to find a solution to this.

This search bar functionality is very complex because it starts with a UI jQuery  plugin (catcomplete), and then adds all sorts of extras. The problem is compounded because the catcomplete plugin creates two ul lists, one in the div below the search bar input tag, and another at the bottom of the page. The one in menu div contains what is seen in the menu, and the one at the bottom of the page contains the filtered items (I think). But I am not entirely sure. The two lists seem to be synchronised by element id's. I think the problems we face arise out of the synchronisation.

Essentially, we have a sorted array of hashes that is added to the top of a js template. The js template then filters the array according to characters in the search bar.

I think we should replace the search bar with a bespoke js function, rather than relying on a highly leveraged jQuery plugin.

**Comment by finanalyst** [comment] 2023-03-02 19:53
closing this issue as complete. Other search  improvements are tracked elsewhere

**Closed by finanalyst** 2023-03-02 19:53 UTC
Labels: search
