### ISSUE TITLE
Padding issues in highlighted code examples

### ISSUE THREAD

**Issue by cfa** [Raku/doc-website#144] opened 2023-02-26 04:43 UTC
Tokens in certain highlighted code blocks are incorrectly spaced due to additional horizontal padding provided by the stylesheet.

There are multiple instances of the problem on the Regexes page; a representative example is the spacing around `:nth`, `:1st`, etc. under the [positional adverb](https://docs-dev.raku.org/language/regexes.html#Positional_adverbs) heading.

The cause appears to be the `section` class in the main stylesheet[^1]

```
.section {
  padding: 3rem 3rem;
}
```

which pads spans like the following

```
<span class="entity name section adverb regexp paren raku"><span>:nth</span></span>
```

[^1]: For screen; there's also a fallback to `1.5rem` in main.css.

**Comment by finanalyst** [comment] 2023-02-26 09:08
Code examples may not be the only styling problem.
Styling comes from several sources: the bulma CSS framework, adaptations for this website, which has separate stylesheets for code and ambient text, adaptations for plugin add ons

**Comment by coke** [comment] 2023-02-27 00:49
Following up from an IRC discussion, it is not just padding around the examples, but *inside* the example itself.

```
$_ = 'The cat chases the dog';
s:global:samecase[the] = 'a';
say $_;                 # OUTPUT: «A cat chases a dog» 
```

is the raw source, but the `s:` here has much more horizontal whitespace inside the example itself; that is, the extra padding isn't just *around* the example.

**Comment by raiph** [comment] 2023-02-27 00:50
![image](https://user-images.githubusercontent.com/1247185/221448479-60c4624b-dde1-4e57-8512-728bf0bc25db.png)

**Comment by coke** [comment] 2023-02-27 00:50
@raiph++ - the issue is the extra horizontal space on (e.g.) the second line between the `s` and the `:`

**Comment by finanalyst** [comment] 2023-02-27 23:38
Closing issue as resolved.

**Closed** 2023-02-27 23:40 UTC
Labels: bug
