### ISSUE TITLE
search for "regex"

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#140] opened 2023-02-25 00:40 UTC
one of the results is "language/regex" - I suspect this should be showing the page title at least.

**Comment by finanalyst** [comment] 2023-04-30 12:18
@coke Not quite sure what the issue is here.
Is the suggestion that when a search candidate is a Rakudoc source file, the Title should be shown in the Info section?

**Comment by coke** [comment] 2023-05-01 17:06
Yes - showing the path to the file isn't helpful.

**Comment by finanalyst** [comment] 2023-05-05 17:17
@coke It's easy to add either the contents of the `=TITLE` or `=SUBTITLE`, both of which must exist by `Raku/doc` rules, to the *info* section of the search bar's candidates list.

Sometimes the TITLE is just as cryptic as the path. `Regex` about has a TITLE of `Regex`. 

But the SUBTITLE can be too long. May be a compromise would be to add the SUBTITLE, chopped at say 100 chars + '...' ?

**Comment by finanalyst** [comment] 2023-05-06 11:04
@coke I've implement a suggested fix for this. 
Try search for `reg` on [new raku](https://new-raku.finanalyst.org)

Also please look at the Pod file there.

**Comment by finanalyst** [comment] 2023-05-06 23:32
@coke changed the search bar to accommodate #249. This works for this issue too.

**Comment by finanalyst** [comment] 2023-10-02 20:53
@coke I think the new search function resolves this issue.

**Closed** 2023-10-02 20:54 UTC
Labels: search
