### ISSUE TITLE
Should also have a link to report a problem with the content / documentation

### ISSUE THREAD

**Issue by lizmat** [Raku/doc-website#221] opened 2023-03-21 10:13 UTC
Currently, there is an easy way to report a problem with the website (which brings you here).

There should also be a link in the "More" pulldown to report a problem with the content, aka the documentation.

**Comment by coke** [comment] 2023-03-22 13:16
We already have tickets that come here; We can easily transfer tickets between github repos. I've updated the ticket template for this repo to point to raku/doc.

I'm not convinced we need this on the site itself, we can't include enough explanatory text there.

**Comment by coke** [comment] 2023-03-22 13:17
Duplicate of #214

**Comment by 2colours** [comment] 2023-03-23 13:54
It's definitely not a bad thing that you did - at least we can revise the possibilities, and I for one definitely prefer having two links.

**Closed** 2023-04-02 19:45 UTC
