### ISSUE TITLE
Switching to another autocomplete plugin for search

### ISSUE THREAD

**Issue by 2colours** [Raku/doc-website#30] opened 2023-01-23 12:24 UTC
https://github.com/Altai-man/docs.raku.org/pull/81

@CIAvash changed the search and this fixed a couple of problems with the fundamentals of it.

Perhaps this site should also adopt that search.

**Comment by finanalyst** [comment] 2023-01-23 18:43
I never did like the Search button on each page in the old website, and I created an extended search tab. Altai-man's enhancement of the Search button is much better in my view.  At the same time, I am not so keen on his ExtendedSearch, which uses essentially the same approach.

However, In order to get this site running as soon as possible, I have ported both the Search button and the ExtendedSearch as closelly as possible to Altai-man's.

My view is that we need another ExtendedSearch, which we can now accommodate neatly in the 'More' drop-down. It is also much easier to create a new ExtendedSearch by creating a new plugin that can operate on the accumulated data in the compilation stage. Data is accumulated for Table of Contents, the Glossary (or Index, basically all the data marked up as `X<>`), and definitions obtained by parsing headers). An example about how to do this can be seen in the `add-search` callable in the ogdenwebb plugin.

**Comment by finanalyst** [comment] 2023-01-31 17:59
Having spoken to Márton @2colours, had some feedback from the Raku zoom meeting,  and given the comment in #47, and Rawley's @rawleyfowler  comments about the search code in general, I think we should replace the code for the search bar. But with what?

Márton has said the autocomplete jQuery plugin is old. 

During the Raku meeting, the ability to use just a keyboard, rather than only mouse clicks, was requested.

This question is about the search bar that is loaded with each page at the top. An extended search page (or pages) can be added later. So given that it is intended as the first place users will go for a quick search, it should be fairly light, and without any fancy filter options.

So, several things:
- which plugin would be better?  If we move away from `autocomplete`.
- what sort of information should be shown? (more about the sorts of information easily available below)
- is the fuzzy search wanted? This allows for misspelling, but also can lead to false positives.

What information is available?
a) We have all the targets in all the files that are used to create Table of contents (TOC). Whenever a `=head` block is encountered in the Rakudoc, a unique id is generated (usually the text of the heading itself), and this is stored for all files in the Collection. This means that we can filter on any word that appears in a heading, and a select will go to that heading in a relevant source.
b) All the targets made by marking up something as `X<>`. I called this 'Glossary' data because the word 'index' is used in HTML and can be confusing. All `X<>` targets for all files are available. So filtering on the Glossary/Index heading, then selecting, will take you to somewhere in source file, where that word/term is marked up.
c) Every title (`=head` block) text is parsed for key words, such as method, sub, infix ..., and a data structure called `defns` is created for all source files. This is how information about, eg, `^..^` is generated.
d) Every source file has a triple of metadata associated with it (kind, subkind, category). This metadata can be found at the top of each file just after the `=pod` declaration

The current search function is provided with information from the last two of these sources. 

> I will note here that the authors of the Rakudoc sources have over time **not** used `X<>` consistently or even correctly. This has reduced very significantly the usefulness of the glossary information. But that is an issue for the doc content repo.

This issue content may be best converted to a discussion. I'll leave that to @coke .

**Comment by finanalyst** [comment] 2023-02-03 11:50
Having thought about this some more, I realised it was trivial to add Heading and Glossary (items marked in source with `X<>`) to the search bar.

Also this is in response to #47 

So I have done this. There is a new PR for this. The new search [can be seen](new-raku.finanalyst.org)

@2colours @rafaelschipiura @rawleyfowler : Some reviews of this extra search info would be good

**Comment by 2colours** [comment] 2023-02-03 16:46
Thank you. I'll try it locally in the evening.

**Comment by 2colours** [comment] 2023-02-04 01:48
I changed the title of this issue a little bit because the main point is not if we take the solution offered by CIAvash. It's the overall question of using a different plugin. If somebody has a better idea or different preference, that also fits here.

**Comment by finanalyst** [comment] 2023-02-05 12:08
I am refactoring the template for the top of the page, creating a separate template for the search-bar. 

This will allow for 
1. the functionality of the search-bar to be placed in a separate plugin
2. other functionality to be developed to substitute the search-bar plugin, without breaking the build of the website.
3. The CSS of the search-bar to be handled separately.

At the end of the refactoring, there will be no user-facing change to the website

**Comment by finanalyst** [comment] 2023-02-05 13:55
Refactoring is complete with PR #77 .  I will be merging in the refactoring this evening in case someone finds a problem caused by the refactoring [see new-raku for an online version of the refactored code](https://new-raku.finanalyst.org)

The current js search function works on an array of objects (in Raku an array of hash) that are generated at build time.

This array is sorted, then filtered on the browser side, and placed into a menu. The filtering and selection could still be done browser side, but it would be more efficient to create the list at the build stage. This would make the browser side filtering faster. 

In addition, because so much has been added to the browser-side processing, we have lost the autocomplete cursor key functionality.

So, I am now working on a refactor of the search-bar assuming a sorted list of objects and a more vanilla autocomplete. I'll look @CIAvash 's work as well.

**Comment by finanalyst** [comment] 2023-02-05 18:09
Having looked at the issue mentioned in the first commit, it seems that in fact the search functionality here is based on Altai-man's work, which included @CIAvash PR.
However, I thought that the `autoComplete` function was from the jQuery UI suite. In fact, it is a pure vanilla function from [Tarek Raafat's source](https://github.com/TarekRaafat/autoComplete.js).

This may be why the cursor key navigating is missing.

**Comment by 2colours** [comment] 2023-02-05 19:22
It could be that the situation was mixed. The "new search" had no categorisation - I even pointed that out as something I kind of miss. Maybe this site started off with "a bit of this, a bit of that", something wasn't completely deleted for example.

**Comment by finanalyst** [comment] 2023-02-05 20:54
It is confusing! Because it looks as both the jQuery and the Raafat autocomplete are being loaded. Since the Raafat one is minimised, its difficult to set a breakpoint in it to see if it's actually called.
Still investigating.

**Comment by finanalyst** [comment] 2023-02-06 13:03
What I want to achieve is a drop-down that describes the element better, remove the enter key event, have the cursor keys select the element, and for the item to be highlighted in drop down menu. Keep the categories with their current styling.

@2colours I think the above takes into account your suggestions. If not, please let me know.

Extended-search needs much more work. Perhaps another issue

**Comment by finanalyst** [comment] 2023-02-08 23:44
Took some time to sort out. The SCSS / CSS for the autocomplete divs were incomplete. Added search-bar theme, and a line in each. 

In fact, the JQuery autocomplete function is used, and not the vanilla js autocomplete library. There was too much work to change completely.

Styling could be better when an element has been selected using a mouse and when moving the cursor down (especially in dark theme).

In addition, if the cursor moves below the menu visible in the browser, it does not scroll up. That requires some more CSS.

If this is an issue for some, then lets open another issue. This one has become too long. So I will close it now with the merge of #89

**Closed by finanalyst** 2023-02-08 23:44 UTC

**Comment by 2colours** [comment] 2023-02-09 10:57
@finanalyst is the new-raku site in the latest "stable" state? Because I can see changes but some important problems seem to persist:

- navigation by keypresses doesn't scroll the drop-down
- the dropdown itself closes when trying to click the scrollbar
- +1 extra: as we know, the jQuery plugin changes the selected element if you hover the categories between the actual elements. However, the highlighting you added, does not - meaning that whenever somebody hovers the category, the "press ENTER to select" caption and the highlight will appear for two different elements. Even though the logic you added makes more sense, I doubt the jQuery plugin will respect it in any way
