### ISSUE TITLE
The search scroll bar cannot be grabbed.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#230] opened 2023-03-27 21:47 UTC
Firefox Version 102.6.0esr (64-bit)
Chromium Version 108.0.5359.124 (Official Build) built on Debian 11.5, running on Debian 11.6 (64-bit)

Clicking on the bar closes the selection box without any other apparent effect.

**Comment by dontlaugh** [comment] 2023-03-28 15:36
I've confirmed/reproduced this. Thanks for the report!

**Comment by dontlaugh** [comment] 2023-03-28 15:37
@finanalyst Can you link to the place in the code where you think this might be fixable? Maybe I can take a stab at it.

**Comment by finanalyst** [comment] 2023-03-30 07:53
I cant respond until the weekend. Sorry

**Comment by finanalyst** [comment] 2023-08-12 12:59
@0rir Please try new UI at new-raku. This is a prototype for the docs.raku.org website. [eg operators](https://new-raku.finanalyst.org/language/operators)
The search function is now in its own side panel, which offers more flexibility and space to manage UI interactions. The scroll bar in particular is more accessible.

**Comment by 0rir** [comment] 2023-08-12 22:02
@finanalyst, very promising.

I go with 'Range':

- The loose/strict logic is reversed.
- I get 20 of 50 items with no way to `next` batch.
- Some labels don't fit in their slide toggles.
- With 'headings' enabled, I get many bare 'In Type: Range' listed.  Clicking one brings me to `/routine/infinite#type/Rangeroutinemethod`.
- Paging back, I am pleasantly disconcerted by a record of my 'history'.  I'm not sure how that will play in practice.
- Long lines are truncated at widget's edge.

I will make new my daily reference.

Thanks.

**Comment by finanalyst** [comment] 2023-10-02 20:20
The original issue seems to be fixed according to @0rir . Closing.

**Closed by finanalyst** 2023-10-02 20:20 UTC
Labels: bug, search
