### ISSUE TITLE
Table is cut in "Programs" page

### ISSUE THREAD

**Issue by melezhik** [Raku/doc-website#155] opened 2023-02-27 16:59 UTC
Please see the screenshot. Tested in safari and chromium 

![table](https://raw.githubusercontent.com/melezhik/images/master/Image%202-27-23%20at%2010.56%20AM.jpeg)

**Comment by coke** [comment] 2023-02-27 17:05
Thanks - duplicate of #106

**Closed by coke** 2023-02-27 17:05 UTC
Labels: UI
