### ISSUE TITLE
Page ToCs are truncated.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#231] opened 2023-03-27 21:53 UTC
The _Table of Contents_ on Type pages have lost info, e.g. _Hash_'s ToC lacks references to methods inherited from _Map_.

**Comment by 2colours** [comment] 2023-03-29 11:28
Only the ToC? I'd say the whole page did. This is quite a bad loss, and probably a weakness of the Collection tool.

**Comment by finanalyst** [comment] 2023-04-02 15:47
@0rir @2colours The problem is the Rakudoc file [`Website/structure-sources/types`](https://github.com/Raku/doc-website/blob/main/Website/structure-sources/types.rakudoc) .

When I first wrote it, there seemed to be a large number of duplicate sections, which I deleted. But they are not duplicates and contained the sections mentioned here.

The issue is resolved by adding in blocks with the relevant search terms (examining the Rakudoc file will explain this better.)

I will revise the Types file in due course, unless someone could help out?

**Comment by finanalyst** [comment] 2023-04-15 17:01
@0rir @2colours I mis-read the issue and thought you were referring to missing categories on the Types page. There are, and I have opened #241 to track this issue.

But the issue mentioned here appears to be part of #204 [See}(https://github.com/Raku/doc-website/issues/104#issuecomment-1435242887)

Is there a need for the extra content in the TOC. It seems to me that Documentable was adding content from other `Type/*` documents. Those documents can directly accessed by clicking on the node in the TypeGraph. Some Types that inherit from many Types would become very large.

**Comment by 2colours** [comment] 2023-04-15 23:20
Will the type graph get an entry in the ToC?

**Comment by finanalyst** [comment] 2023-04-16 16:49
@2colours It should. But I haven't worked out how yet.

**Comment by 0rir** [comment] 2023-04-16 18:15
@finanalyst, It is not clear to me that the other three mentioned issues are the same plaint as this one.  And the type graphs don't need to be on the page's ToC -- more below.

(I'd prefer to verify my memory on all the below but don't know how.)

Previously, a type's ToC would list the local methods of the class, then continue by listing parents' methods.  For sub-`Cool` classes, I think it stopped at `Cool`.  At least, I don't recall seeing  `Any`'s junction methods lower down.   This extra length of the ToCs has never bothered me because of their repetitive nature--just bail if you know.  The more comprehensive ToC is handy for one searching for some behavior whilst unsure of the class and/or the method  name.

Historically the type-graph was just appended to the page, not in the ToC.  As a naive beginner, I had no expectation regarding their existence or locations.  Finding a couple was easy training to expect them.  The ToC entry for a graph seems useless when the chart is against a solid UI wall.
A bottom of page button would do as well.
    An issue could be a type graph tool and/or a graph section or index on the language page.  The index would be to what is; a tool or section a likely expansion of the set of graphs.

The renditions of some graphs seem different.  I think the `Str` graph previously skipped over or through `Allomorph`.  And the `Code` graph use to include `ForeignCode`.  Weird.

**Comment by 2colours** [comment] 2023-04-16 19:56
Okay, so we are back to "this is how I used it all the time, this is what I want back" sort of arguments... I think these are problematic for two reasons:
- without an a priori consensus, they don't lead anywhere. Everybody can just say how they used the site and if it doesn't match, we haven't reached anywhere
- they are overly prone to *survivor bias*, i.e if the previous way itself _was the reason people stayed away_, we are going to just reassure the problem without even noticing

The two arguments to consolidate that I think are worth representing are:
- knowing the interface of a "type" is a fundamental goal of the official documentation; it's way too reductional to only have the topmost layer
- common base types, like `Any` or `Cool`, proliferate the interface quite significantly which makes lookup inconvenient at times

Supporting the second point, I for one have missed `Any` stuff often, and were bothered by "irrelevant" `Cool` stuff often, both have happened to me.

To throw something additional in: I think it would be really good to actually have a complete (as in, _complete_ complete, nothing missing) list of available methods for all types, NOT organized by roles and base classes. This could be a mere alphabetic list of links that one can toggle for hide/show, and it doesn't have to be exclusive, i.e other ways to present and order content is also fine.  
Or, phrased in a broader way, have some way in the documentation to tell if `Type.method` is gonna fly or not, not having to consult Rakudo sources all the time. For me, that would be the game changer thing, and I do think it is somewhere along the lines an important goal of any reference to provide efficient means to do something like that.

**Comment by 0rir** [comment] 2023-04-17 04:16
@2colours, you misread me.   There is little "this is what I want back" to be inferred from my statements.  Stating the way things were, is to help us (mostly @finanalyst, I guess) get back to what  prior consensus **did** settle upon.  That is the state from which to move forward.  Because the tool set changed, I only look for the functionality--not the presentation.

I did try to seed readers' minds with the idea of a type-graph tool or section as I contemplate an issue.   I am going off-topic more now, because of not knowing whether a task efficiently combines with near term work.

A doc tool section and/or distributed doc tools appear to be things we both would appreciate.

As a Raku advocate, I wish to make the docs more accessible to  the newcomers.  I found the extended ToC method listings helpful.  Sometimes irksome, yes,  but repeated eyes-on was, and is, helpful for navigating the data.  Reviewing `Mu` now, I don't feel I suffered for it not being in the ToCs.

`Str.^methods( :all)`, etc., seems to give the raw data necessary to avoid the Rakudo sources. I have munged much dirtier data.  Are you willing to consider collaboration?  Could be the `cdecl` of Raku!

**Comment by 2colours** [comment] 2023-04-17 10:54
> get back to what prior consensus **did** settle upon

I wouldn't assume it went any differently to how we are doing things these days. Of course, if you have some sort of evidence of such a consensus that I'm not aware of, do correct me.

> As a Raku advocate, I wish to make the docs more accessible to the newcomers. I found the extended ToC method listings helpful. Sometimes irksome, yes, but repeated eyes-on was, and is, helpful for navigating the data. Reviewing `Mu` now, I don't feel I suffered for it not being in the ToCs.

I for one have definitely felt both, i.e that there is too much garbage piling up that makes me just feel distressed when wanting to just get an overview, and that `Any` (if not `Mu`) is missing to have a failproof, "properly closed" entity.  [This recent PR](https://github.com/Raku/doc/pull/4284) comes to mind. `Buf` and `Blob` aren't `Iterable` and therefore they cannot have `flat` called on them, for example - however, they do provide an implementation of `˙list` which is just enough for `map` to be called on them. Would you know that by heart?

> `Str.^methods( :all)`, etc., seems to give the raw data necessary to avoid the Rakudo sources. I have munged much dirtier data.

No doubt you have and I also have. However, I think to provide and present this in some reasonable way would be along the lines the goal of the docs, not only because you might not have a Raku runtime at your disposal when you want to read the docs - but also because this line is plain nontrivial Rakudo. I think we still didn't make up our minds to push everything from Rakudo into the Raku language so it's kinda touchy to even advise something like this in the official documentation. Also, if somebody wants to understand how and why something like this works, they need to grasp how the metamodel works in Rakudo.

> Are you willing to consider collaboration? Could be the `cdecl` of Raku!

To be honest, I didn't understand this part completely, could you reiterate please?

**Comment by 0rir** [comment] 2023-04-17 19:47
WARNING, this continues the off-topic  @2colours -- @0rir discussion off-topic for this issue.
I think punning the `Buf` role would use or override the `Any.list` method; as a  client user, it is most efficient it I don't need to know.

I think you are saying: that such a method listing tool is poor because rakudo-isms pollute the output, requiring a  Raku runtime is a negative, and that getting such a method-lister blessed into the official documentation is unlikely.    I am unsure why it is important for a method-lister user to understand how the lister works.

Such a lister would be useful with all those negatives.  Such a lister might aid in the marking of implementation and rakudo-specific methods with `.WHY` or otherwise.

The tool could/should be  in two parts:  a database builder and a presenter.

A tool should prove its worth before being in the current https://raku.org/resources/ .  Getting it into "Doc" proper would be  more exclusive.

> Are you willing to consider collaboration? Could be the cdecl of Raku!

I may over-explain since I'll expand all of that.

`cdecl` is a still in use program evolving from the 1980's.  It takes a C declaration and states it in English:  `char *(*foo[][8])()` is roughly  like  _foo is array of array of array of 8 pointers to functions returning pointers to char_.

As for the collaboration question, if you are willing to work  on such a listing tool, you might find people  with whom to work.  I am in that group, but I recognize that the difference in our skills might have me being dead weight instead of an assist.

**Comment by finanalyst** [comment] 2023-04-18 10:00
One issue for me here is that source files under the `Raku/docs/doc/Type` directory are treated differently to other source files. 

When other source files are generated only the data in the source file is added. This means that the content of a page generated from the source file is strictly  determined by the author of the source file.

For **Type** source files, once the render of the source has been completed, a check is made to see whether an svg file with the same filename exists, and if it does, it is added to the end of the source (which is why it is not so easy  to add it to the ToC, which has already been rendered by this time).

The svg files are generated by another tool and they are based on a text file that contains information about inheritance. The text file is quite short and the dependencies are calculated recursively. (By the way: the difference between the different graphs depends on the `dot` graph generator. Three files only are generated using a different renderer, see the Typegraph module.)

Personally, I think that information to be included in a page should be determined by the source file.

The Typegraph diagrams are a reasonable exception to the above principle because it is a generic rule. Omitting the Typegraph diagrams was immediately noticed and so there seems to be a consensus that they should be included.

The methods generated for each type by collecting together the methods for each ancestor by looking at those source files recursively seems to me to be excessive. @2colours  mentioned this is the case in some situations. So a single generic rule seems to have pro's and con's

However, knowing which methods are available in a Type because they are available in ancestor Types does seem to me to be useful. But I wonder whether this information could be presented in a different way. Maybe another section called `available methods` which lists them together with links to the Secondary pages ?
> secondary pages are composite files generated from all primary files.

It seems to me that we should create a new consensus about the extra information (if any) that should be added to all **Type** sources. Even if we arrive at something that looks like the previous page, at least we will have a clearer description to implement.

**Comment by 2colours** [comment] 2023-04-18 16:09
I decided to delete the long message I was getting towards It started feeling pointless. I think @finanalyst summarized the situation well, also giving us some insight about how things work or could work.

@0rir I'm not sure you got my point about how `Buf` can be iterated but you would have to arbitrarily dig to figure it out. To keep the rest shorter than originally: a tool would be better than to tell someone to invoke MOP-ish code that isn't even standard Raku, however, I don't know where my place would be in this. I see that you have an actual idea about how to start off, and that deserves respect and admiration imo. I have been jumping around a lot for like half a year by now; I have tried to take up on community modules (mostly `Template6`), `mi6` then `Ddt`, Rakudo bugs, certain RakuAST challenges I was curious about, `SpitSH`, documentation content and presentation - and most recently the Atom highlighter. Oh right, also some private stuff... it all blends together. The best thing would be to settle on something for a while, For now, I can only say: if you can actually set off and you require help with the implementation of something in particular, count me in, I'll try to help...

**Comment by finanalyst** [comment] 2023-06-21 22:56
I have just reviewed the whole thread in this issue again. It started in one place and moved to another topic. It seems from all comments that the new site has a reasonable balance between adequate information and too much detail. So closing this issue as complete.
Please re-open with a concrete suggestion about how to improve

**Closed by finanalyst** 2023-06-21 22:56 UTC
