### ISSUE TITLE
Sentence fragments:  'See primary documentation...'

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#422] opened 2024-12-09 19:39 UTC
The referring line(s) starting results for the composite choices is  lacks a trailing non-bold period.
This may be fixed at or about line 149 in Website/plugins/secondaries/gen-secondaries.raku.  I am not sure if  a period needs protection for the subsequent template processing.

**Comment by finanalyst** [comment] 2024-12-28 17:57
@0rir 
- Fixing now, thanks for digging to find where the problem is.
- FYI: This is a website creation issue, rather than  a content issue. 
- I don't often check  issues here, but I do on Raku/docs-website

**Comment by finanalyst** [comment] 2024-12-28 19:10
closing as completed

**Closed by finanalyst** 2024-12-28 19:10 UTC
