### ISSUE TITLE
Searching for `\` gives a 404.

### ISSUE THREAD

**Issue by defaultxr** [Raku/doc-website#288] opened 2023-08-24 01:36 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://docs.raku.org/
2. Click on the search bar
3. Type `\`
4. Press `enter` to accept the first entry, for the syntax documentation for `\`.
5. You will be sent to https://docs.raku.org/syntax/%5C , which is a 404 page.

**Expected behavior**
Searching for `\` should return syntax documentation for `\`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Vivaldi (Chromium-based)
 - Version 6.1.3035.302

**Comment by 2colours** [comment] 2023-08-24 11:37
Thank you for the report.

It seems to me that this URL is actually invalid, with a couple of others that the search can recommend. Both archive.org and [Altai_man's still running alternative site](http://164.90.207.89:10010/syntax/%5C) miss content for it.

I found a few similarly problematic recommendations when typing `.` into the search bar:

![image](https://github.com/Raku/doc-website/assets/37218286/9aa426c4-ba1a-4020-b515-c15d058c1bef)

- the first one points to https://docs.raku.org/routine/ which is 404 on the new site and [checking the archive version](https://web.archive.org/web/20201111230716/https://docs.raku.org/routine/), it was outright faulty on the old site, resolving to `index`. [Altai_man's version](http://164.90.207.89:10010/routine) returned a dummy page which I think is still more valid
- the second one points to https://docs.raku.org/syntax/ which is currently an arbitrary "[From language/5to6-nutshell](https://docs.raku.org/syntax/#___top)" entry, even though it didn't use to exist and it's a custom 404 site on Altai_man's site as well
- the third one seems to act as a "folder up" hard link and takes you outright to https://docs.raku.org/

For comparison, the `...` entry of the search works properly.

**Comment by finanalyst** [comment] 2023-08-30 08:29
One of these cases, `\` does not cause a problem with the new search routine. It should be linking to `UNSPACE` in syntax.

**Comment by finanalyst** [comment] 2023-09-23 21:25
@defaultxr @2colours The fault for `.` is due to incorrect escaping. The regex is fixed in the new search routine. Please test on [new-raku development site](https://new-raku.finanalyst.org)

`\` is not working with new-raku, but works with cro-app. More investigation is needed.

The problem is only with `\` on its own. When used with another character, it works, eg. `\c`.

**Comment by defaultxr** [comment] 2023-09-24 18:11
> Please test on [new-raku development site](https://new-raku.finanalyst.org/)

`.` works on the new site, but `\` does not appear to work on it (as you mentioned).

**Comment by 2colours** [comment] 2023-09-26 09:20
Fortunately, I decided to check it for myself. I don't know what you guys mean by "works". For me, it's the exact same behavior as it used to be, yes, on the new-raku development site. The `.` from language/regexes points to https://new-raku.finanalyst.org/syntax/ which is still a "Perl to Raku" introduction, the `.` from language/operators points to https://new-raku.finanalyst.org/routine/ which is still a custom 404 page, and `..` from language/operators still takes back to the main site https://new-raku.finanalyst.org/.

**Comment by finanalyst** [comment] 2023-09-27 17:46
@2colours I just checked the behaviour on [new-raku](https://new-raku.finanalyst.org). Like @defaultxr , searching on `.` gives me a few options. The one labelled 'from /regexes' generates a URL with `.../syntax/.` and opens to a valid file, the one labelled 'from /operators' generates a URL with `.../routines/.` and also opens to a valid file.
Please make sure that you are not getting an old cached version of the web site. Let me know if you still have a problem with `.` and `..`. 
I'm very puzzled by the `\` candidate, so I'm looking at it soon.

**Comment by 2colours** [comment] 2023-09-27 22:51
@finanalyst I have just opened it in a different browser that I haven't used in years and I get the same (wrong) behavior.

**Comment by finanalyst** [comment] 2023-09-29 09:48
@2colours please share which browsers you have tested, and which OS.
- I am wondering whether the problem is related to using URLs with '.' '..' '\' (when they are the only characters) as file names (when \ or . are combined with another character, the problem disappears). I think we are at the bleeding edge here.
- We may need to rename the source so that eg '.' is rewritten as `. <character>` and `\<space>`

**Comment by 2colours** [comment] 2023-09-29 12:45
Running a Windows 10, build 19045, main browser is Maxthon 7.1.6.1000 (with useragent `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`) but I get the same behavior with Microsoft Edge 117.0.2045.43 (user agent is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43`).

And indeed I can type the link with `syntax/.` all I want, I get `syntax/`.

**Comment by finanalyst** [comment] 2023-09-30 15:13
@2colours The URL actually passed by the search engine is 'syntax/%2E' which should be shown as `syntax/.` This is the behaviour for all other Unicode characters.
So I think the safest workaround is to change the source for these three items. They are all in `Language/operators.rakudoc` (I think).
Also, just for clarity, the section on 'UNSPACE' should be labelled in some way as `\ followed by space`, because it should be `\    `, not `\`. The trailing white space is trimmed by the regexes.
My suggestions would be
- `. (single period)`
- `.. (double period)`
- `\  (backslash followed by space[s])`

**Comment by 2colours** [comment] 2023-09-30 21:25
I think that's fair enough. (By the way, indeed: even if I type `syntax/%2E` in the URL, it wil still be reduced to nothing after the slash.)

**Comment by finanalyst** [comment] 2023-10-01 21:17
@2colours I am trying to fix this in the secondaries plugin, so that it doesn't NEED fixing in the sources. However, I think the sources should be fixed in any case for the sake of clarity.

Also I discovered another anomaly. Some composite files are named `syntax/` and others `routine/`. The changes are related to how the information is gathered. But I do not see any reason for this distinction.
In particular there is a file `syntax/.` and also `routine/.` The logic of having **Composite** pages is to gather information about the same name but in different contexts. So I would think there should only be one `. (as a name)` composite file. 
What do you think? Unless you can think of a reason, I will raise an issue in the Docs/ repo.

**Comment by 2colours** [comment] 2023-10-01 21:43
Yes, probably... honestly, I don't know how this works. There are a lot of `syntax/` links out there, even for stuff that doesn't seem like syntax to me. But if there is some basis to the distinction, probably the only reason why both `syntax/.` and `routine/.` should exist is if the dot is so overloaded that it has meaning for both categories.

**Comment by finanalyst** [comment] 2023-10-01 21:47
@2colours I just discovered that if you type `\` into the browser, you get it automatically made into a `/` !!!

**Comment by finanalyst** [comment] 2023-10-01 22:35
@2colours @defaultxr I think I have solved this problem.
Try [new-raku eg reference](https://new-raku.finanalyst.org/reference)
Try typing `\` or `.` (there are two separate entries, try both) or `..`
They all should go to some appropriate content

If you can get these to work, then I'll put in a PR here.

**Comment by finanalyst** [comment] 2023-10-02 20:19
This is now fixed. Closing. @2colours please re-open if you still get problems.

**Closed by finanalyst** 2023-10-02 20:19 UTC
Labels: bug, search

**Comment by 2colours** [comment] 2023-10-03 09:11
Yes, this looks good. Thank you.
