### ISSUE TITLE
Annoying double scrollbar

### ISSUE THREAD

**Issue by juanfra684** [Raku/doc-website#300] opened 2023-09-18 22:59 UTC
**Describe the bug**
There are 2 scrollbars in https://docs.raku.org/language/containers. Attached screenshot.

**To Reproduce**
1. Go to https://docs.raku.org/language/containers with a Chromium based browser or Firefox.

**Expected behavior**
Only 1 scrollbar.

**Screenshots**
![1](https://github.com/Raku/doc-website/assets/180453/40e67fbf-0e93-448d-9088-6bac0d1d48ad).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium based browser or Firefox
 - Version: latest.
 
**Fix?**
All works as expected when I disable `height: 92vh;` in `<div style="height: 92vh; overflow-y: scroll; flex-grow:inherit;">`, just bellow of `<div id="main-column" class="tile is-parent" style="overflow-x: hidden;">`. The code was introduced in the commit https://github.com/Raku/doc-website/commit/d7e875477df9f2b036b57b2a40df97b10ccb0fbd. This is the line: https://github.com/Raku/doc-website/blob/82a5fb4c5fa19d7460b599431802610507d225b1/Website/plugins/page-styling/page-styling.raku#L166

**Comment by finanalyst** [comment] 2023-09-19 12:24
Good catch. Thanks.

 FYI This is an updated interface and you are using it in the tablet or
mobile mode (the hamburger is visible in the top right). There's been less
testing in this format.

Thanks for finding a good fix. I'll deal with this as soon as possible.

**Comment by finanalyst** [comment] 2023-09-20 20:15
Also is visible in desktop.

**Comment by finanalyst** [comment] 2023-09-20 21:09
@juanfra684 This behaviour is not as simple as I thought. The problem is that when the height of the tile containing the main text is removed (which is your suggestion), then the contents panel, when opened does not stay fixed. By setting the height of the main tlie, the contents tile scrolls independently.

It would probably be best to make the rightmost scroll bar invisible. There are some fixes on stackoverflow, but they dont seem to work here.

Still working on this. The relevant  SCSS is in `Website/plugins/page-styling/scss/_themes-templates-common.scss`

**Comment by donaldh** [comment] 2023-12-01 22:38
Please don't try to hide the rightmost /  outermost scrollbar. That's _the_ scrollbar that gets the keyboard focus when you visit any page on the site. That's the only scrollbar you want on the page since it's the one that makes the page keyboard accessible.

I suggest that removing `height: 92vh;` is a good interim step to fix the double scrollbar problems. After fixing that, we can explore if there is a good way to have a separately scrollable content tile.

**Comment by donaldh** [comment] 2023-12-01 23:29
The python docs seem to have more or less the right behaviour. E.g.

https://docs.python.org/3/whatsnew/3.6.html

From what I see there it's this combination of CSS properties on the sidebar that works:
```
float: none;
position: sticky;
top: 0;
max-height: 100vh;
```

I think if you apply that to `div id="left-column"` and apply `overflow-y: scroll` to `div class="raku-sidebar"` then the "Table of Contents" header and the filter box will remain static while the sidebar content will be scrollable.

<img width="362" alt="image" src="https://github.com/Raku/doc-website/assets/465955/b3d4b621-4f0b-4630-b0f7-bdef39d989eb">

**Comment by finanalyst** [comment] 2023-12-07 16:02
@donaldh @juanfra684 I've just added a patch to fix this. @donaldh +1 for hints. It took a bit of fiddling to get something that worked with everything else.
Please look at the concept site [new-raku, eg. operators](https://new-raku.finanalyst.org/language/operators) and see if the change works with your browser/OS.

**Comment by finanalyst** [comment] 2023-12-07 17:13
@juanfra684 @donaldh This change should now be visible on [doc-dev](https://docs-dev.raku.org).
Feedback would be welcome before the change goes to the production site.

**Comment by donaldh** [comment] 2023-12-07 22:33
The concept site works well and seems to completely solve the issue. The docs-dev site still has the double scrollbar for me.

**Comment by finanalyst** [comment] 2023-12-14 16:29
@donaldh synched deploy and docs-dev. works for me now. closing as completed

**Closed by finanalyst** 2023-12-14 16:29 UTC
