### ISSUE TITLE
Provide keyboard shortcut for focusing the "Search" field

### ISSUE THREAD

**Issue by vadz** [Raku/doc-website#210] opened 2023-03-08 14:40 UTC
As discussed in #209, it would be nice to be able to search entirely from keyboard, without using mouse at all.

I'm not aware of any formal recommendations about how this should be implemented, but all "biggish" sites I know of, including GitHub itself, seem to use about the same approach which works rather well IME:

1. Focus the search fields if <kbd>/</kbd> is pressed.
2. Also focus the search field if <kbd>Ctrl+F</kbd> is pressed, but show a message saying that pressing it again will use the browser built-in search.
3. Of course, do use the browser built-in search if <kbd>Ctrl+F</kbd> is pressed again.

As an alternative, some sites open a search popup rather than just focusing the search window, this allows to show more information, e.g. some instructions, in it. Some sites have a checkbox "[ ] Open on Ctrl+F" and clearing it makes <kbd>Ctrl+F</kbd> use the built-in search directly.

But globally the important thing is that <kbd>/</kbd> can always be used for searching and <kbd>Ctrl+F</kbd> can be also used for it optionally, but without taking away the possibility to use the built-in search.

**Comment by yabobayy** [comment] 2023-03-23 12:00
Also `Alt+Shift+F` like in the previous version, and like in Wikipedia.

**Comment by lucs** [comment] 2023-03-23 14:14
I would be happy with plain slash to enter the search box. I would avoid Ctrl-F, since many browsers already use it for searching in an open web page (although @finanalyst's suggestion is not unreasonable), and as for Alt-Shift-F, ain't nobody got time for that :-) (but why not, eh).

**Comment by yabobayy** [comment] 2023-03-23 14:19
> I would be happy with plain slash to enter the search box. I would avoid Ctrl-F, since many browsers already use it for searching in an open web page (although @finanalyst's suggestion is not unreasonable), and as for Alt-Shift-F, ain't nobody got time for that :-) (but why not, eh).

It's always possible to add multiple shortcuts

**Comment by finanalyst** [comment] 2023-08-12 13:11
@vadz @lucs @yabobayy please test the new UI at new raku [see example here](https://new-raku.finanalyst.org/language/operators). 

Hovering over the search and ToC toggles in the top left and top right give information about the keyboard shortcuts. Currently, the keyboard shortcuts are for the whole of the document, which is intuitive for most users. But it would be possible to restriict them so they only fire when the cursor is in the top navigation bar.

The shortcuts over-ride any browser defaults.

**Comment by vadz** [comment] 2023-08-22 07:32
Thanks for the new version! I've looked at it, and it seems to work as designed, but I have to admit that having sidebars on both sides looks a bit weird to me. Could they both leave on the left hand side instead somehow (e.g. different tabs, or just one on top of the other)?

A couple of very minor issues:

1. The gear icons don't seem to really do anything and at least the one near "Search" seems superfluous.
2. There is a missing ")" in the tooltip for "Search", it says "Toggle search sidebar (Ctl-s" (and, BTW, using "Ctl" as abbreviation for "Control" is non-standard).

Also, I'd still rather use `/` or `Ctrl+F` as the shortcut instead of `Ctrl+S` for search.

**Comment by finanalyst** [comment] 2023-08-30 08:32
@vadz Thanks for the feedback. Not having two sidebars seems to be a common idea.

**Comment by finanalyst** [comment] 2023-09-14 23:43
@vadz I got `/` to focus on the search, together with Ctrl-F. The problem is that it is not possible to search for the character `/` !!! I'm sure there is a clever way around this problem, but is it really worth the hassle? 
The new search function, together with various shortcuts for the search options can be found on [new-raku](https://new-raku.finanalyst.org).

**Comment by vadz** [comment] 2023-09-16 13:23
Sorry, I've just tested it again and there are unfortunately a couple of problems in the latest version:

1. When the search field is not shown, e.g. when the window is not wide enough, neither `Ctrl+F` nor `/` work, when they would be _especially_ useful exactly in this situation.
2. When the search is shown, they both do focus it but `/` also puts a literal slash into the search, which has to be deleted before searching for anything else.

If possible, it would be really great to make (1) work, i.e. make the shortcuts show the search field even if it's currently hidden.

Thanks again!

**Comment by finanalyst** [comment] 2023-10-02 20:29
All these issues have been considered in the refactored search . Shortcut has been added, shortcut opens search bar if hidden.
The actual shortcut key strokes caused debate so Alt-F was chosen.
@coke please review for closing this issue

**Comment by vadz** [comment] 2023-10-02 20:32
Sorry again, but `Alt-F` doesn't work at all for me: under Linux Firefox it just opens the "File" menu.

**Comment by finanalyst** [comment] 2023-10-02 20:47
@vadz please delete the local storage data and reload. Since you have been testing you may have settings that are not the default.
On Firefox, use F12 to open the developers panel, then chose the 'storage' tab (its after Memory on the top bar), then 'Local Storage' in the left-hand vertical bar, then click on the docs.raku.org domain, right click over the 'keys' column, and the option delete all is quite safe. Then reload.

Also, check the Navigation bar on the web page, chose 'More' to get a drop down. Make sure that the 'shortcuts' toggle is set to enabled. 

If the shortcuts are disabled, the Firefox defaults will be activated.

**Comment by vadz** [comment] 2023-10-02 20:54
Oops, you're right, very sorry for a false alarm, after cleaning up it works as expected, great!

**Comment by finanalyst** [comment] 2023-10-02 20:57
@vadz great. I'm closing this issue as resolved.

**Closed by finanalyst** 2023-10-02 20:57 UTC
Labels: search
