### ISSUE TITLE
`<word>` constructs in code samples needs protecting from being trated as HTML tags

### ISSUE THREAD

**Issue by vrurg** [Raku/doc-website#272] opened 2023-07-29 14:54 UTC
## Problem

The code samples are currently protected with bare `<pre>` but no quoting is done for HTML-unsafe constructs. Therefore, `:mode<rw>` on [this page](https://docs.raku.org/type/IO/Handle#method_write), in particular, is displayed as plain `:mode`.

![image](https://github.com/Raku/doc/assets/1586992/723d79e2-827f-4733-ba62-0af44a79a8ab)

**Comment by finanalyst** [comment] 2023-07-31 11:21
@vrurg I looked at this in more detail. I found the bug about two weeks ago, and fixed it. The PR has now been accepted. Normally, changes to MAIN are reflected in a develop site and the date of the update can be seen at [developer docs](https://docs-dev.raku.org/about). Occasionally Main and docs-dev get out of sync. docs-dev is currently 10 days old.

However, you can see that the problem is fixed by looking at [my version of the page](https://new-raku.finanalyst.org/type/IO/Handle#method_open)

**Comment by finanalyst** [comment] 2023-07-31 13:27
@vrurg The issue is resolved. See [IO open on docs-dev](https://docs-dev.raku.org/type/IO/Handle#method_open)

It may take time for docs-dev to migrate to docs

**Comment by finanalyst** [comment] 2023-08-07 10:40
closing as completed

**Closed by finanalyst** 2023-08-07 10:40 UTC
