### ISSUE TITLE
Site Search issues

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#166] opened 2023-02-28 17:34 UTC
Just based on the poor usability of the primary search bar; this interface is not ready to be the default for accessing the docs. 

Since eyes-on will help, I suggest a "Check out the new system that's on the way".

With the --I'll call it-- static system, I could at least shrink the font to see the entire main search drop down when it exceeded window Y-ness.  That is no longer possible, and the scroll bars cause the drop down to vanish.

I try to look up `proto`, I type it in and it is presumably in text to which I might scroll; but can't.

The filtering mechanism of the search field is unhelpful.  Experimenting I find that `proto` was visible after a few letters typed, but as more is the filter lets more off-topic items into the list.

These comments involve:  Firefox 102.6.esr (64-bit)  and
Chromium Version 108.0.5359.124 (Official Build) built on Debian 11.5, running on Debian 11.6 (64-bit)

And Chromium has transparency issues with the above-mentioned drop down and with the page ToC sidebar.

**Comment by coke** [comment] 2023-02-28 17:39
> Just based on the poor usability of the primary search bar; this interface is not ready to be the default for accessing the docs.

FYI, it is now the default for accessing the docs, went live this weekend. Thanks for the feedback, there are changes planned and we'll try to address the points raised here.

**Comment by finanalyst** [comment] 2023-10-02 20:51
@0rir this issue has been taken into consideration with the new search refactoring. I think the issue is resolved.
Please review the new search and close this issue if resolved.

**Closed** 2023-10-06 15:49 UTC
Labels: search
