### ISSUE TITLE
Sometimes can't click "About" or "Report an issue…"

### ISSUE THREAD

**Issue by lucs** [Raku/doc-website#225] opened 2023-03-23 14:59 UTC
I'm using the Brave browser, "Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) unknown (64-bit)".

The problem occurs when clicking either of those from the "More" dropdown when the browser window is wide enough to display it directly. It appears as though the click just transparently goes through and my cursor lands somewhere in the "Raku™ documentation" title.

The click works fine when the window is narrower, from under the "More" that appears under the hamburger dropdown.

**Comment by coke** [comment] 2023-03-23 15:25
FYI: on standard chrome on windows/mac, with either width, both links work here. Assuming something about Brave.

**Comment by dontlaugh** [comment] 2023-03-23 16:38
Closing as dupe of #226

**Closed by dontlaugh** 2023-03-23 16:38 UTC
